// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhmdfznmxddsgjtyqnnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobWRmem5teGRkc2dqdHlxbm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjMyNTQsImV4cCI6MjA2OTQ5OTI1NH0.Y2BwWdy_CoDZcibxzFw7JFxuVleDaHW4hdeHrgEok0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});